version: '3.8'

services:
  # Main Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starwars-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    environment:
      - APP_NAME="Star Wars App"
      - APP_ENV=production
      - APP_KEY=base64:r4RE7US+p3WlXDsLb2nGDFT6/xhaJ8kZlV2UEkk4vtY=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=starwars_app
      - DB_USERNAME=starwars_user
      - DB_PASSWORD=starwars_password
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    depends_on:
      - mysql
    networks:
      - starwars-network

  # Web server (Nginx)
  nginx:
    image: nginx:alpine
    container_name: starwars-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
      - ./storage/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - starwars-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: starwars-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: starwars_app
      MYSQL_USER: starwars_user
      MYSQL_PASSWORD: starwars_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - starwars-network

  # Job Scheduler
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starwars-scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan schedule:work
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_NAME="Star Wars App"
      - APP_ENV=production
      - APP_KEY=base64:r4RE7US+p3WlXDsLb2nGDFT6/xhaJ8kZlV2UEkk4vtY=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=starwars_app
      - DB_USERNAME=starwars_user
      - DB_PASSWORD=starwars_password
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    depends_on:
      - mysql
    networks:
      - starwars-network

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starwars-queue
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_NAME="Star Wars App"
      - APP_ENV=production
      - APP_KEY=base64:r4RE7US+p3WlXDsLb2nGDFT6/xhaJ8kZlV2UEkk4vtY=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=starwars_app
      - DB_USERNAME=starwars_user
      - DB_PASSWORD=starwars_password
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    depends_on:
      - mysql
    networks:
      - starwars-network

volumes:
  mysql_data:
    driver: local

networks:
  starwars-network:
    driver: bridge
